### ISSUE TITLE
Offset in pack water output

### ISSUE THREAD

**Issue by henriasv** [henriasv/molecular-builder#15]
There seems to be an offset in the positions of the solid atoms when packing water. The following script produces a quite serious case: 

```python
from molecular_builder import create_bulk_crystal, carve_geometry, fetch_prepared_system, write, pack_water
from molecular_builder.geometry import BoxGeometry

blob = fetch_prepared_system("ch_blob/10nm", type_mapping=[(1, 6), (2, 1)])
blob.positions[:,2] += 37

slab = fetch_prepared_system("vashishta_1990_like_amorphous_silica/quench_950K", type_mapping=[(1, 14), (2, 8)])
slab.cell[2,2] += 110

sodium_chlorate = create_bulk_crystal("sodium_chlorate", size=(slab.cell[0,0] ,slab.cell[1,1], 25), round="down")
carve_geometry(sodium_chlorate, BoxGeometry([slab.cell[0,0]*3/4, slab.cell[1,1]/2, 0], [slab.cell[0,0]/2, slab.cell[1,1]+100, 5]), side="in")
sodium_chlorate.translate((0,0,118))

atoms = (slab + blob) + sodium_chlorate

write(atoms, "indenter_and_glass.data")

pack_water(atoms, 10000,pbc=2.0, tolerance=2.0)

write(atoms, "indenter_and_glass.data")
write(atoms, "indenter_and_glass.png", 
            camera_dir=(0,1,0), 
            viewport_type="orthogonal", 
            bond_specs=[("O", "H", 0.95), ("Si", "O", 1.9)], 
            atom_radii=[("Si", 0.2), ("O", 0.6)])
```

![indenter_and_glass](https://user-images.githubusercontent.com/1681822/90890294-fb223780-e3b9-11ea-80cb-3c73089d1c1e.png)
It is clear that the solid has been displaces when the water was packed, resulting in packing water outside of the silica slab at the bottom.

**Comment by evenmn** [comment]
This seems to be a packmol issue rather than a molecular-builder issue. The offset in z-direction is caused by the "center" keyword in the packmol input script. When removing this keyword and setting "fixed 0 0 0 0 0 0", the offset in z-direction disappears. 
![displaced_z](https://user-images.githubusercontent.com/31393910/91725653-57960b80-eb9f-11ea-80b2-f7787b278182.png)

However, the system is still displaced in all directions:
![displaced_xy](https://user-images.githubusercontent.com/31393910/91725708-667cbe00-eb9f-11ea-8548-36132c629c8f.png)

It appears that the system is displaced exactly 10Å in all directions. We get the expected result when setting "fixed 10 10 10 0 0 0". 
![nooffset](https://user-images.githubusercontent.com/31393910/91725912-ac398680-eb9f-11ea-96b3-d4bc83fa577e.png)

This is a workaround that works for this particular system, and might not work for other systems. The packmol developers are now aware of the issue.
